# Generated by Django 4.1.2 on 2023-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(max_length=30000)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
