# Generated by Django 4.1.2 on 2023-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Date', models.DateField()),
                ('time', models.TimeField()),
                ('Phone_number', models.IntegerField()),
            ],
        ),
    ]
