# Generated by Django 4.1.2 on 2023-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_bookings_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(upload_to='main/images'),
        ),
    ]
